-- Description: Creates the raw table for restaurant inspection data

DROP TABLE IF EXISTS Inspected_RestaurantData;

CREATE TABLE Inspected_RestaurantData (
    RES_ID NVARCHAR(20),
    RES_NAME NVARCHAR(100),
    BORO NVARCHAR(20),
    BUILDING NVARCHAR(20),
    STREET NVARCHAR(100),
    ZIPCODE NVARCHAR(10),
    PHONE_NUMBER NVARCHAR(20),
    CUISINE_DESCRIPTION NVARCHAR(MAX),
    INSPECTION_DATE DATE,
    ACTION NVARCHAR(MAX),
    VIOLATION_CODE NVARCHAR(10),
    VIOLATION_DESCRIPTION NVARCHAR(MAX),
    CRITICAL_FLAG NVARCHAR(30),
    SCORE INT,
    GRADE NVARCHAR(10),
    GRADE_DATE DATE,
    RECORD_DATE DATE,
    INSPECTION_TYPE NVARCHAR(100),
    INSPECTION_YEAR INT,
    INSPECTION_MONTH INT,
    INSPECTION_DAY INT,
    INSPECTION_WEEK_NUMBER INT,
    RISK_CATEGORY NVARCHAR(20),
    FULL_ADDRESS NVARCHAR(MAX)
);